### ISSUE TITLE
KeyError: 'S783' when run  NextDay-240,1-LSTM.py

### ISSUE THREAD

**Issue by elife33** [pushpendughosh/Stock-market-forecasting#1]
(tensorflow) (base) elife@ubuntu:~/work/Trading/Stock-market-forecasting$ python NextDay-240,1-LSTM.py
/usr/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From NextDay-240,1-LSTM.py:10: The name tf.keras.layers.CuDNNLSTM is deprecated. Please use tf.compat.v1.keras.layers.CuDNNLSTM instead.

WARNING:tensorflow:From NextDay-240,1-LSTM.py:22: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

----------------------------------------
1993
----------------------------------------
Traceback (most recent call last):
  File "NextDay-240,1-LSTM.py", line 181, in <module>
    st_train_data,st_test_data = create_stock_data(df,st)
  File "NextDay-240,1-LSTM.py", line 137, in create_stock_data
    daily_change = df[st].pct_change()
  File "/home/elife/tensorflow/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/home/elife/tensorflow/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/home/elife/tensorflow/local/lib/python2.7/site-packages/pandas/core/generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "/home/elife/tensorflow/local/lib/python2.7/site-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/home/elife/tensorflow/local/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'S783'
(tensorflow) (base) elife@ubuntu:~/work/Trading/Stock-market-forecasting$

**Comment by pushpendughosh** [comment]
Please note that the names of the stock in SPXconst.csv should match the names of stocks in files with adjusted close and adjusted open prices.
This happened because the above condition failed.
Please go through: https://github.com/pushpendughosh/Stock-market-forecasting/blob/master/data/README.md
For testing purpose, I would update the dummy datas so that it at least runs.

**Comment by pushpendughosh** [comment]
I corrected the dummy data files, which will help you run all the codes for the year 1993. So clone the Github repo again, and then run the python files. 
Note that the dummy files are a copy of the true data from Bloomberg, scaled and added with gaussian noise. 
I hope that helps.

**Comment by pushpendughosh** [comment]
I corrected the dummy data files, which will help you run all the codes for the year 1993. So clone the Github repo again, and then run the python files.
Note that the dummy files are a copy of the true data from Bloomberg, scaled and added with gaussian noise.
I hope that helps.

**Comment by elife33** [comment]
Thanks, it works now. By the way, for NextDay-240,1-LSTM.py, it needs directory models3 and results3 existed.

**Comment by pushpendughosh** [comment]
Yes true, that will be a good idea, if I create the necessary folders (if they don't exist), while execution.
Sure I will add the changes.

**Comment by pushpendughosh** [comment]
> Yes true, that will be a good idea, if I create the necessary folders (if they don't exist), while execution.
> Sure I will add the changes.

I added the necessary changes for the same to all python files.
```
for directory in [model_folder,result_folder]:
    if not os.path.exists(directory):
        os.makedirs(directory)
```

**Comment by pushpendughosh** [comment]
Closing the issue.
