### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' 

### ISSUE THREAD

**Issue by mh-github** [pushpendughosh/Stock-market-forecasting#3]
My environment
Windows 10
conda environment with scikit-learn==0.20.4 & tensorflow==1.14.0
==========================================================
**python -Wignore "Intraday-240,1-LSTM.py"**

WARNING:tensorflow:From Intraday-240,1-LSTM.py:11: The name tf.keras.layers.CuDNNLSTM is deprecated. Please use tf.compat.v1.keras.layers.CuDNNLSTM instead.

----------------------------------------
1993
----------------------------------------
(251416, 244) (121079, 244) 109.14551615715027
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 240, 1)]          0
_________________________________________________________________
cu_dnnlstm (CuDNNLSTM)       (None, 25)                2800
_________________________________________________________________
dropout (Dropout)            (None, 25)                0
_________________________________________________________________
dense (Dense)                (None, 2)                 52
=================================================================
Total params: 2,852
Trainable params: 2,852
Non-trainable params: 0
_________________________________________________________________
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of samples seen.
Train on 201132 samples, validate on 50284 samples
2021-09-02 12:44:05.181180: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\client\session.py", line 1339, in _run_fn
    self._extend_graph()
  File "C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\client\session.py", line 1374, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by {{node cu_dnnlstm/CudnnRNN}}with these attrs: [seed=0, dropout=0, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="lstm", seed2=0, is_training=true]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

         [[cu_dnnlstm/CudnnRNN]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Intraday-240,1-LSTM.py", line 194, in <module>
    model,predictions = trainer(train_data,test_data)
  File "Intraday-240,1-LSTM.py", line 89, in trainer
    batch_size=512
  File "C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\keras\engine\training.py", line 780, in fit
    steps_name='steps_per_epoch')
  File "C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 250, in model_iteration
    model.reset_metrics()
  File "C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1084, in reset_metrics
    m.reset_states()
  File "C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\keras\metrics.py", line 199, in reset_states
    K.batch_set_value([(v, 0) for v in self.variables])
  File "C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\keras\backend.py", line 3071, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\keras\backend.py", line 462, in get_session
    _initialize_variables(session)
  File "C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\keras\backend.py", line 879, in _initialize_variables
    [variables_module.is_variable_initialized(v) for v in candidate_vars])
  File "C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "C:\ProgramData\Anaconda3\envs\myenv1\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
**tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by node cu_dnnlstm/CudnnRNN (defined at Intraday-240,1-LSTM.py:44) with these attrs: [seed=0, dropout=0, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="lstm", seed2=0, is_training=true]
Registered devices: [CPU]**
Registered kernels:
  <no registered kernels>

         [[cu_dnnlstm/CudnnRNN]]

**Comment by pushpendughosh** [comment]
CuDNNLSTM is designed for CUDA parallel processing and cannot run if there is no GPU. I guess your machine does not have GPU support. You may try running the code on Googla colab platform or simply change "CuDNNLSTM" to "LSTM". 

Read: https://stackoverflow.com/a/57308344

**Comment by mh-github** [comment]
Hi Pushpendu
Could you ever run this code on Windows?

My computer does not have an integrated gpu but it does have a graphics card: 2 GB NVidia GeForce GT 710. That won't do?

![image](https://user-images.githubusercontent.com/2176303/132094439-5c166b17-a13b-46b5-a3c7-8c683760fe97.png)

The problem seems to be getting it registered with tensorflow.

![image](https://user-images.githubusercontent.com/2176303/132094462-8030b994-d32e-4d90-ac79-19a38d2ff61f.png)
